version: "3"
services:
  web:
    build: .
    ports:
     - 13000:3000
    links:
     - mongo
  mongo:
    image: "mongo:3.6.5"
    ports:
     - 27017:27017
    volumes:
     - /Users/giovanni/opt/workspaces/NodeSamples/nodetest1/data/db:/data/db